// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import EmotionFormController from "./emotion_form_controller"
application.register("emotion-form", EmotionFormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MobileNavigationController from "./mobile_navigation_controller"
application.register("mobile-navigation", MobileNavigationController)

import MoodGridController from "./mood_grid_controller"
application.register("mood-grid", MoodGridController)

import QuadrantChartController from "./quadrant_chart_controller"
application.register("quadrant-chart", QuadrantChartController)

import UsersIndexController from "./users_index_controller"
application.register("users-index", UsersIndexController)
