services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - ai
      - redis
      - sidekiq
    environment:
      AI_SERVICE_URL: "http://ai:11434"
      REDIS_URL: "redis://redis:6379/0"

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - ".:/app"
    depends_on:
      - db
      - ai
      - redis
    environment:
      REDIS_URL: "redis://redis:6379/0"
    restart: unless-stopped

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  db:
    image: "postgres:17.4"
    volumes:
      - "echomood_postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "echomood_development"
    ports:
      - "5432:5432"

  ai:
    image: "ollama/ollama:latest"
    volumes:
      - "ollama_data:/root/.ollama"
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          memory: 8G
    command: "serve"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  echomood_postgres_data:
  ollama_data:
